### ISSUE TITLE
When adding custom styles using card configuration, only the first is applied

### ISSUE THREAD

**Issue by clarinetJWD** [clarinetJWD/bolder-weather-card#11]
Using this config:

```
styles:
  - variable: bolder-weather-card-border-radius
    value: 60px
  - variable: bolder-weather-card-border-width
    value: 100px
```

Only the border-radius is applied.
