### ISSUE TITLE
Temperature Sensor not Respecting decimal precision

### ISSUE THREAD

**Issue by Ledfoot775** [clarinetJWD/bolder-weather-card#20]
![Image](https://github.com/user-attachments/assets/ff7a041f-7fa2-43e6-ab1f-5d2e2ec9bec7)

**Checklist:**
- [x] I updated to the latest version available
- [x] I cleared the cache of my browser
- [x] I read the [[FAQ](https://github.com/clarinetJWD/bolder-weather-card#faq)](https://github.com/clarinetJWD/bolder-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:**
Latest version

**Last working release (if known):**
Unknown

**Browser and Operating System:**
Chrome/Chromium on MacOS and Linux

**Description of problem:**
Awesome work on this weather card!

I've found a bug related to temperature precision display. The Bolder Weather Card is displaying temperature with 2 decimal places, ignoring the precision setting of the temperature sensor.

As shown in the screenshot I've shared, the card displays "14.53°C" with two decimal places, while my temperature sensor is configured with a precision of 1 decimal place and should display as "14.5°C".

I'm using the card with the following configuration:
```yaml
type: custom:bolder-weather-card
entity: weather.xxxxxx
sun_entity: sun.sun
use_day_night_colors: false
temperature_sensor: sensor.backyard_sensor_hue_z2m_temperature
hide_today_section: false
hide_clock: true
hide_date: true
show_humidity: false
show_decimal: true
hourly_forecast: false
forecast_rows: "7"
grid_options:
  columns: 18
  rows: auto
styles:
  - variable: primary-text-size
    value: 120pt
  - variable: state-text-size
    value: 60pt
  - variable: state-text-space-below
    value: 0pt
  - variable: forecast-grid-gap
    value: 1rem
  - variable: forecast-bar-height
    value: 2.0rem
  - variable: forecast-text-size
    value: 2.0rem
  - variable: forecast-col-day-size
    value: 4.0rem
  - variable: forecast-col-icon-size
    value: 3.0rem
  - variable: forecast-col-temp-low-size
    value: 5.0rem
  - variable: forecast-col-temp-high-size
    value: 2.0rem
  - variable: border-radius
    value: 7pt
card_mod:
  style: |
    ha-card {
      background: none !important;
      border: none !important;
    }
```

The issue is that the temperature sensor has a precision set of 1 decimal place, but the card is not respecting that and is showing the raw value with 2 decimal places.

note the backyard temp card on the left and the weather card are both using the same source temperature sensor.

![Image](https://github.com/user-attachments/assets/30d529dc-6a56-4991-9992-46297146b642)

![Image](https://github.com/user-attachments/assets/d0c7bae0-09b1-4446-a78b-069cfa78b223)
