### ISSUE TITLE
Add ability to style card via templates

### ISSUE THREAD

**Issue by clarinetJWD** [clarinetJWD/bolder-weather-card#25]
**Is your feature request related to a problem? Please describe.**
Add the ability to use templates to change style values, specifically text colors.

**Describe the solution you'd like**
When specifying in-configuration styles, something like this should change the color based on the value in `weather_color`:

```yaml
styles:
  - variable: text-color
    value: |
      {{ states('input_text.weather_color') }}
```
