### ISSUE TITLE
'today-image-max-width' style option doesn't work in Panel (single card) view.

### ISSUE THREAD

**Issue by tismondo** [clarinetJWD/bolder-weather-card#27]
I'd like to display this card in a HA "panel" view but when I do, the weather icons get blown up to an obscene size, and it won't respond to resizing manually with 'today-image-max-width' (and height) style options

I've tested the exact same card config in the masonry and sidebar views and confirmed the style option works as expected. But the moment I switch the view to "panel", the icon goes bonkers and refuses to be fixed.

![Image](https://github.com/user-attachments/assets/6b0c90a8-1c57-4e59-bf72-41808d26f76e)

```
type: custom:bolder-weather-card
entity: weather.forecast_home
title: Weather
use_day_night_colors: false
aqi_sensor: sensor.u_s_air_quality_index
aqi_use_color: true
time_format: "12"
hide_today_section: false
hide_clock: true
hide_date: true
show_humidity: true
show_decimal: false
hourly_forecast: false
forecast_rows: "6"
use_time_as_primary: false
show_low_high_on_primary: false
show_dots_between_primary_elements: false
use_browser_time: false
sun_entity: sun.sun
styles:
  - variable: bolder-weather-card-today-image-max-width
    value: 100%
  - variable: bolder-weather-card-today-image-max-height
    value: 100%
```

FANTASTIC CARD, by the way - this is the weather card of my dreams, and I love the customizability.

**Checklist:**

- [check] I updated to the latest version available
- [check] I cleared the cache of my browser
- [check] I read the [FAQ](https://github.com/clarinetJWD/bolder-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:** 1.91

**Last working release (if known):** N/A

**Browser and Operating System:**

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
